#version: '3.8'

services:
  frontend:
    container_name: constructi-frontend
    build:
      context: ./constructi-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - constructi-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    extends:
      file: ./constructi-backend/docker-compose.yml
      service: backend

  postgres:
      extends:
        file: ./constructi-backend/docker-compose.yml
        service: postgres

networks:
  constructi-network:
    driver: bridge

volumes:
  constructi-backend_postgres-data:
