#version: '3.8'

services:
  backend:
    image: constructi-api:latest
    container_name: constructi-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Constructi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=action
    depends_on:
      - postgres
    ports:
      - "8086:8086"
    networks:
      - constructi-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: Constructi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: action
#      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
#      - postgres-data:/var/lib/postgresql/data
       - constructi-backend_postgres-data:/var/lib/postgresql/data
#      - ./init-scripts:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"
    networks:
      - constructi-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  constructi-network:
    driver: bridge

volumes:
  constructi-backend_postgres-data:
