name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permission for Maven wrapper
        run: chmod +x ./constructi-backend/mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test Spring Boot application
        working-directory: ./constructi-backend
        run: ./mvnw clean test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./constructi-frontend
        run: npm install

      - name: Run Angular tests
        working-directory: ./constructi-frontend
        run: npm run test

  build-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permission for Maven wrapper
        run: chmod +x ./constructi-backend/mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot application
        working-directory: ./constructi-backend
        run: ./mvnw clean package

      - name: Build Docker image for backend
        working-directory: ./constructi-backend
        run: docker build -t constructi-backend .

  build-frontend:
    runs-on: ubuntu-latest
    needs: test-frontend
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./constructi-frontend
        run: npm install

      - name: Build Angular application
        working-directory: ./constructi-frontend
        run: npm run build -- --configuration production

      - name: Build Docker image for frontend
        working-directory: ./constructi-frontend
        run: docker build -t constructi-frontend .

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d